app:
    name: "Flickr Sync"
    version: "2014-09-17"

finder:
    in: "test"

flickr:
    oauth:
        siteUrl: "https://www.flickr.com/services/oauth/"
        consumerKey: ef41e52674a4572bd9c05c1df0a3c9a4
        consumerSecret: 077c25b4411d432c

monolog:
    handlers:
        console:
            type: console